name: Update Pages

on:
  repository_dispatch:  # Triggers when API call is made to GitHub
    types: [update-profiles]

jobs:
  update:
    runs-on: ubuntu-latest
    environment: env1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install --upgrade -r script/reqs.txt

      - name: Run update script
        env:
          API_URL: ${{ secrets.API_URL }}
          API_KEY: ${{ secrets.API_PASSWORD }}
        run: |
          cd script
          python update.py

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add site/
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update pages"
          git push
